services:
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ytrewq

volumes:
  db_value:
